import pandas as pd

data = [
    ("love", "positive"),
    ("deeply", "positive"),
    ("worst", "negative"),
    ("okay", "neutral"),
    ("fantastic", "positive"),
    ("never", "negative"),
    ("not", "neutral"),
    ("sure", "neutral"),
    ("everyone", "neutral"),
    ("hate", "negative"),
    ("joy", "positive"),
    ("sad", "negative"),
    ("amazing", "positive"),
    ("terrible", "negative"),
    ("fine", "neutral"),
    ("good", "positive"),
    ("bad", "negative"),
    ("uncertain", "neutral"),
    ("wonderful", "positive"),
    ("disaster", "negative"),
    ("average", "neutral"),
    ("great", "positive"),
    ("problem", "negative"),
    ("normal", "neutral"),
    ("excellent", "positive"),
    ("fail", "negative"),
    ("acceptable", "neutral"),
    ("delightful", "positive"),
    ("awful", "negative"),
    ("indifferent", "neutral"),
    ("content", "positive"),
    ("upset", "negative"),
    ("mediocre", "neutral"),
    ("stunning", "positive"),
    ("fiasco", "negative"),
    ("typical", "neutral"),
    ("superb", "positive"),
    ("disappointing", "negative"),
    ("plain", "neutral"),
    ("thrilled", "positive"),
    ("miserable", "negative"),
    ("satisfactory", "neutral"),
    ("brilliant", "positive"),
    ("ruined", "negative"),
    ("common", "neutral"),
    ("splendid", "positive"),
    ("dreadful", "negative"),
    ("adequate", "neutral"),
]

df = pd.DataFrame(data, columns=['text', 'sentiment'])
csv_file_path = 'sentiment_dataset.csv'
df.to_csv(csv_file_path, index=False)
print("CSV file generated")
